# https://github.com/Canop/broot/issues/120
# A popular set of shorctuts for going up and down:
#
[[verbs]]
key = "ctrl-j"
execution = ":line_down"

[[verbs]]
key = "ctrl-k"
execution = ":line_up"

[[verbs]]
key = "ctrl-d"
execution = ":page_down"

[[verbs]]
key = "ctrl-u"
execution = ":page_up"

[[verbs]]
key = "ctrl-q"
execution = ":quit"
