#!/bin/bash

noisly() {
  i3-msg workspace 8
  sleep 1
  URL1="https://music.youtube.com/"
  URL2="https://www.noisli.com/playlists"
  nohup google-chrome --new-window $URL1 &
  sleep 1
  nohup google-chrome $URL2 &
  # sleep 1
  # gnome-terminal -- /usr/bin/bashtop &
  # nohup gnome-system-monitor &
  sleep 1
  i3-msg '[workspace="8"]' move workspace to output eDP-1
  # exit
}
